### PR TITLE
Unnatural Hunger > Famished

### PR DESCRIPTION
**Pull request by IcarussOne**
Renames the Unnatural Hunger effect to Famished, it still fits the effect because the definition is "extreme hunger". This was done to prevent the name from overlapping with the GUI because of how long it is.
effect

### CODE REVIEW

**Comment by TheCodex6824** [comment]
We can rename it if we really have to, but it would be nice to keep it the same so people don't get confused. Give this a try:

1. Put `#PARSE_ESCAPES` on the first line of the lang file
2. Try making the value `Unnatural\nHunger` (note the \n there)

If that renders correctly, then I think we should use that. Otherwise, renaming it is probably the simplest option.

**Comment by xJon** [comment]
I will say, extreme hunger is not quite same as unnatural hunger, and doesn't make as much sense in-game with rotten flesh.

**Comment by TheCodex6824** [comment]
"Unhunger" might not be a bad name, although I think the lang key is just a shorter version of "unnatural hunger" and didn't mean to make a new term for it. The new name should ideally communicate that you can't help it by eating normal food, although I thought there was some text that appeared if you tried to eat normal food so at least the name isn't the only indicator.

**Comment by TechnoMysterio** [comment]
There should be text that appears when you eat the wrong type of food, though of course I haven't checked to see if that still works in TC6. Unhunger does sound like a very good shorthand though, so I'd opt for that myself.

**Pull request merged**
